// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: frequencia.proto

package frequencia

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Analisador_AnalisarTexto_FullMethodName = "/frequencia.Analisador/AnalisarTexto"
)

// AnalisadorClient is the client API for Analisador service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Serviço compartilhado
type AnalisadorClient interface {
	AnalisarTexto(ctx context.Context, in *TextoRequest, opts ...grpc.CallOption) (*ResultadoResponse, error)
}

type analisadorClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalisadorClient(cc grpc.ClientConnInterface) AnalisadorClient {
	return &analisadorClient{cc}
}

func (c *analisadorClient) AnalisarTexto(ctx context.Context, in *TextoRequest, opts ...grpc.CallOption) (*ResultadoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultadoResponse)
	err := c.cc.Invoke(ctx, Analisador_AnalisarTexto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalisadorServer is the server API for Analisador service.
// All implementations must embed UnimplementedAnalisadorServer
// for forward compatibility.
//
// Serviço compartilhado
type AnalisadorServer interface {
	AnalisarTexto(context.Context, *TextoRequest) (*ResultadoResponse, error)
	mustEmbedUnimplementedAnalisadorServer()
}

// UnimplementedAnalisadorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalisadorServer struct{}

func (UnimplementedAnalisadorServer) AnalisarTexto(context.Context, *TextoRequest) (*ResultadoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalisarTexto not implemented")
}
func (UnimplementedAnalisadorServer) mustEmbedUnimplementedAnalisadorServer() {}
func (UnimplementedAnalisadorServer) testEmbeddedByValue()                    {}

// UnsafeAnalisadorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalisadorServer will
// result in compilation errors.
type UnsafeAnalisadorServer interface {
	mustEmbedUnimplementedAnalisadorServer()
}

func RegisterAnalisadorServer(s grpc.ServiceRegistrar, srv AnalisadorServer) {
	// If the following call pancis, it indicates UnimplementedAnalisadorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Analisador_ServiceDesc, srv)
}

func _Analisador_AnalisarTexto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalisadorServer).AnalisarTexto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analisador_AnalisarTexto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalisadorServer).AnalisarTexto(ctx, req.(*TextoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Analisador_ServiceDesc is the grpc.ServiceDesc for Analisador service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Analisador_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frequencia.Analisador",
	HandlerType: (*AnalisadorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalisarTexto",
			Handler:    _Analisador_AnalisarTexto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frequencia.proto",
}
