// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: frequencia.proto

package frequencia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texto         string                 `protobuf:"bytes,1,opt,name=texto,proto3" json:"texto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextoRequest) Reset() {
	*x = TextoRequest{}
	mi := &file_frequencia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextoRequest) ProtoMessage() {}

func (x *TextoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frequencia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextoRequest.ProtoReflect.Descriptor instead.
func (*TextoRequest) Descriptor() ([]byte, []int) {
	return file_frequencia_proto_rawDescGZIP(), []int{0}
}

func (x *TextoRequest) GetTexto() string {
	if x != nil {
		return x.Texto
	}
	return ""
}

type Metricas struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TempoProcessamentoNanos int64                  `protobuf:"varint,1,opt,name=tempo_processamento_nanos,json=tempoProcessamentoNanos,proto3" json:"tempo_processamento_nanos,omitempty"`
	WorkersUsados           int32                  `protobuf:"varint,2,opt,name=workers_usados,json=workersUsados,proto3" json:"workers_usados,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Metricas) Reset() {
	*x = Metricas{}
	mi := &file_frequencia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metricas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metricas) ProtoMessage() {}

func (x *Metricas) ProtoReflect() protoreflect.Message {
	mi := &file_frequencia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metricas.ProtoReflect.Descriptor instead.
func (*Metricas) Descriptor() ([]byte, []int) {
	return file_frequencia_proto_rawDescGZIP(), []int{1}
}

func (x *Metricas) GetTempoProcessamentoNanos() int64 {
	if x != nil {
		return x.TempoProcessamentoNanos
	}
	return 0
}

func (x *Metricas) GetWorkersUsados() int32 {
	if x != nil {
		return x.WorkersUsados
	}
	return 0
}

type ResultadoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalPalavras  int32                  `protobuf:"varint,1,opt,name=total_palavras,json=totalPalavras,proto3" json:"total_palavras,omitempty"`
	PalavrasUnicas int32                  `protobuf:"varint,2,opt,name=palavras_unicas,json=palavrasUnicas,proto3" json:"palavras_unicas,omitempty"`
	Contagem       map[string]int32       `protobuf:"bytes,3,rep,name=contagem,proto3" json:"contagem,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Mapa de frequência
	Top_5          []string               `protobuf:"bytes,4,rep,name=top_5,json=top5,proto3" json:"top_5,omitempty"`                                                                        // Lista das top palavras
	Metricas       *Metricas              `protobuf:"bytes,5,opt,name=metricas,proto3" json:"metricas,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResultadoResponse) Reset() {
	*x = ResultadoResponse{}
	mi := &file_frequencia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoResponse) ProtoMessage() {}

func (x *ResultadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frequencia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoResponse.ProtoReflect.Descriptor instead.
func (*ResultadoResponse) Descriptor() ([]byte, []int) {
	return file_frequencia_proto_rawDescGZIP(), []int{2}
}

func (x *ResultadoResponse) GetTotalPalavras() int32 {
	if x != nil {
		return x.TotalPalavras
	}
	return 0
}

func (x *ResultadoResponse) GetPalavrasUnicas() int32 {
	if x != nil {
		return x.PalavrasUnicas
	}
	return 0
}

func (x *ResultadoResponse) GetContagem() map[string]int32 {
	if x != nil {
		return x.Contagem
	}
	return nil
}

func (x *ResultadoResponse) GetTop_5() []string {
	if x != nil {
		return x.Top_5
	}
	return nil
}

func (x *ResultadoResponse) GetMetricas() *Metricas {
	if x != nil {
		return x.Metricas
	}
	return nil
}

var File_frequencia_proto protoreflect.FileDescriptor

const file_frequencia_proto_rawDesc = "" +
	"\n" +
	"\x10frequencia.proto\x12\n" +
	"frequencia\"$\n" +
	"\fTextoRequest\x12\x14\n" +
	"\x05texto\x18\x01 \x01(\tR\x05texto\"m\n" +
	"\bMetricas\x12:\n" +
	"\x19tempo_processamento_nanos\x18\x01 \x01(\x03R\x17tempoProcessamentoNanos\x12%\n" +
	"\x0eworkers_usados\x18\x02 \x01(\x05R\rworkersUsados\"\xb0\x02\n" +
	"\x11ResultadoResponse\x12%\n" +
	"\x0etotal_palavras\x18\x01 \x01(\x05R\rtotalPalavras\x12'\n" +
	"\x0fpalavras_unicas\x18\x02 \x01(\x05R\x0epalavrasUnicas\x12G\n" +
	"\bcontagem\x18\x03 \x03(\v2+.frequencia.ResultadoResponse.ContagemEntryR\bcontagem\x12\x13\n" +
	"\x05top_5\x18\x04 \x03(\tR\x04top5\x120\n" +
	"\bmetricas\x18\x05 \x01(\v2\x14.frequencia.MetricasR\bmetricas\x1a;\n" +
	"\rContagemEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012V\n" +
	"\n" +
	"Analisador\x12H\n" +
	"\rAnalisarTexto\x12\x18.frequencia.TextoRequest\x1a\x1d.frequencia.ResultadoResponseB\x1eZ\x1cstopwords_project/frequenciab\x06proto3"

var (
	file_frequencia_proto_rawDescOnce sync.Once
	file_frequencia_proto_rawDescData []byte
)

func file_frequencia_proto_rawDescGZIP() []byte {
	file_frequencia_proto_rawDescOnce.Do(func() {
		file_frequencia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frequencia_proto_rawDesc), len(file_frequencia_proto_rawDesc)))
	})
	return file_frequencia_proto_rawDescData
}

var file_frequencia_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_frequencia_proto_goTypes = []any{
	(*TextoRequest)(nil),      // 0: frequencia.TextoRequest
	(*Metricas)(nil),          // 1: frequencia.Metricas
	(*ResultadoResponse)(nil), // 2: frequencia.ResultadoResponse
	nil,                       // 3: frequencia.ResultadoResponse.ContagemEntry
}
var file_frequencia_proto_depIdxs = []int32{
	3, // 0: frequencia.ResultadoResponse.contagem:type_name -> frequencia.ResultadoResponse.ContagemEntry
	1, // 1: frequencia.ResultadoResponse.metricas:type_name -> frequencia.Metricas
	0, // 2: frequencia.Analisador.AnalisarTexto:input_type -> frequencia.TextoRequest
	2, // 3: frequencia.Analisador.AnalisarTexto:output_type -> frequencia.ResultadoResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_frequencia_proto_init() }
func file_frequencia_proto_init() {
	if File_frequencia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frequencia_proto_rawDesc), len(file_frequencia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frequencia_proto_goTypes,
		DependencyIndexes: file_frequencia_proto_depIdxs,
		MessageInfos:      file_frequencia_proto_msgTypes,
	}.Build()
	File_frequencia_proto = out.File
	file_frequencia_proto_goTypes = nil
	file_frequencia_proto_depIdxs = nil
}
